version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20 
    commands:
      - npm install
  pre_build:
    commands:
  build:
    commands:
    
  post_build:
    commands:
artifacts:
  type: zip
  files:
    - '**/*'
cache:
  paths:
    - node_modules